name: Test (PyPI)

on:
  schedule:
    - cron: "0 18 * * *"

jobs:
  test:
    name: ${{ matrix.platform }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test
        with:
          python-version: ${{ matrix.python-version }}
          install-packages: "'stardist-napari[test]'"
